name: test_demo_app

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt_deps
      run: sudo apt-get install -y xxd lldb
    - name: get_tensorflow
      run: git submodule update --init --recursive
    - name: post_build
      run: |
        chmod a+x binder/postBuild
        sh binder/postBuild
    - name: check_demo
      run: ./simple_app/demo
