name: compile

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive     
    - name: apt_deps
      run: sudo apt-get install -y xxd lldb
    - name: compile
      run: |
        chmod a+x binder/postBuild
        sh binder/postBuild
